services:
  pgadmin:
    image: dpage/pgadmin4:9
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      postgres:
        condition: service_healthy
#  mongo:
#    image: mongo:7
#    restart: unless-stopped
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo_data:/data/db
#    healthcheck:
#      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
#      interval: 10s
#      timeout: 5s
#      retries: 10

#  clickhouse:
#    image: clickhouse/clickhouse-server:24
#    restart: unless-stopped
#    ports:
#      - "8123:8123"
#      - "9000:9000"
#    volumes:
#      - ch_data:/var/lib/clickhouse
#    ulimits:
#      nofile:
#        soft: 262144
#        hard: 262144
#    healthcheck:
#      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
#      interval: 10s
#      timeout: 5s
#      retries: 30
#      start_period: 20s

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: dwv
      POSTGRES_PASSWORD: dwv
      POSTGRES_DB: dwv
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dwv -d dwv"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    volumes:
      - ./frontend/public:/app/frontend/public
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "dwv"
      POSTGRES_USER: "dwv"
      POSTGRES_PASSWORD: "dwv"
    ports:
      - "8000:8000"

  scraper_scheduler:
    build:
      context: ./scraper
    restart: unless-stopped
    depends_on:
#      mongo:
#        condition: service_healthy
#      clickhouse:
#        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
#      MONGO_URI: "mongodb://mongo:27017"
#      CLICKHOUSE_HOST: "clickhouse"
#      CLICKHOUSE_HTTP_PORT: "8123"
      UN_API_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZWxlbHZzZXJAZ21haWwuY29tIiwiZW1haWwiOiJiZWxlbHZzZXJAZ21haWwuY29tIiwidW5pcXVlX25hbWUiOiJiZWxlbHZzZXJAZ21haWwuY29tIiwibmJmIjoxNzczNjk4MTE5LCJleHAiOjE4MDUyMzQxMTksImlhdCI6MTc3MzY5ODExOSwiaXNzIjoiZG90bmV0LXVzZXItand0cyIsImF1ZCI6ImRhdGEtcG9ydGFsLWFwaSJ9.KiQmyRHYmQvY0afAaKIo_d236vQhCYFXIes9sDWcRlM"

      # Postgres (добавили)
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "dwv"
      POSTGRES_USER: "dwv"
      POSTGRES_PASSWORD: "dwv"

      SCRAPE_INTERVAL_MINUTES: "60"
      SCRAPER_COMMAND: "python main.py"

      LOG_DIR: "/logs"
    volumes:
      - ./scraper:/app
      - ./logs:/logs
    command: ["python", "scheduler.py"]

volumes:
  mongo_data:
  ch_data:
  pg_data:
