services:
  pgadmin:
    image: dpage/pgadmin4:9
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: dwv
      POSTGRES_PASSWORD: dwv
      POSTGRES_DB: dwv
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dwv -d dwv"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "dwv"
      POSTGRES_USER: "dwv"
      POSTGRES_PASSWORD: "dwv"
    ports:
      - "8000:8000"

  scraper_scheduler:
    build:
      context: ./scraper
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      UN_API_TOKEN: "..."
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "dwv"
      POSTGRES_USER: "dwv"
      POSTGRES_PASSWORD: "dwv"
      SCRAPE_INTERVAL_MINUTES: "60"
      SCRAPER_COMMAND: "python main.py"
      LOG_DIR: "/logs"
    volumes:
      - ./scraper:/app
      - ./logs:/logs
    command: ["python", "scheduler.py"]

volumes:
  mongo_data:
  ch_data:
  pg_data:
  pgadmin_data:
